# Generated by Django 6.0 on 2026-01-13 06:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistanceApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AddField(
            model_name='airesponselog',
            name='feedback_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airesponselog',
            name='was_helpful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistancechat',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistancechat',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistancemessage',
            name='ai_response_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='helpful_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faq',
            name='not_helpful_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airesponselog',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='assistanceApp.assistancechat'),
        ),
        migrations.AlterField(
            model_name='airesponselog',
            name='response_time',
            field=models.FloatField(help_text='Response time in seconds'),
        ),
        migrations.AlterField(
            model_name='assistancechat',
            name='status',
            field=models.CharField(choices=[('ai_handled', 'AI Handled'), ('human_requested', 'Human Assistance Requested'), ('human_responding', 'Human Responding'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='ai_handled', max_length=20),
        ),
        migrations.AlterField(
            model_name='assistancemessage',
            name='message_type',
            field=models.CharField(choices=[('user_question', 'User Question'), ('ai_response', 'AI Response'), ('human_response', 'Human Response'), ('system', 'System Message')], max_length=20),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('account', 'Account'), ('mentorship', 'Mentorship'), ('billing', 'Billing')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_to', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_sent', models.BooleanField(default=False)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_responses', to='assistanceApp.assistancechat')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
