# Generated by Django 6.0 on 2026-01-13 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistanceApp', '0002_alter_faq_options_airesponselog_feedback_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistancechat',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='assistancechat',
            name='anonymous_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='assistancechat',
            name='linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistancechat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistance_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
