# Generated by Django 6.0 on 2026-01-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingmodule',
            name='multimedia_files',
            field=models.JSONField(default=list, help_text='List of multimedia files (images, videos, audio, documents)'),
        ),
        migrations.AlterField(
            model_name='onboardingmodule',
            name='resources',
            field=models.JSONField(default=list, help_text='List of external resources (links to documents, websites, etc.)'),
        ),
    ]
